---
# tasks file for webserver
- name: Install Apache Packages 
  apt: name=apache2 state=present
  when: ansible_os_family == "Debian"

- name: Start Apache Service 
  service: name=apache2 state=started
  when: ansible_os_family == "Debian"

- name: Install HTTPD Packages 
  yum: name=httpd state=present
  when: ansible_os_family == "RedHat"

- name: Start HTTPD Service 
  service: name=httpd state=started
  when: ansible_os_family == "Redhat"

- name: Deploy Custom Web Page
  copy: src=files/index.html dest={{doc_root}}

- name: Deploy Custom Info Web Page
  template: src=templates/info.j2 dest={{doc_root}}/info.html
